spring:
  #rabbitmq配置
  rabbitmq:
    username: yuqian
    password: yuqian
    addresses: 101.43.57.111:5672
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  application:
    name: my-rabbitMq-manual
server:
  port: 11563